name: python-workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          python3 -m flake8 main.py
          python3 -m flake8 sum.py
      - name: Lint with black
        run: |
          pip install black==21.5b1
          python -m black main.py
        with:
          options: "--check --verbose"
          src: "./"
          jupyter: true
          version: "21.5b1"
      - name: Test with Pytest
        run: |
          python3 -m pytest sum.py --doctest-modules